---
# Two distinct identities so we can register two distinct SPIFFE IDs in
# the SWA control plane:
#   spiffe://murphys-lab.local/ns/swa-demo/sa/mtls-server
#   spiffe://murphys-lab.local/ns/swa-demo/sa/mtls-client
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtls-server
  namespace: swa-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtls-client
  namespace: swa-demo
